docker/sync-wrap/src/handlers.js, ecs-proxies-containers.yml, ecs-proxies-deploy.yml
=> apm-1017: stop deploying async-slowapp

Makefile, azure-pipelines.yml
=> apm-1131: test new branch

azure/azure-release-pipeline.yml
=> apm-1266: add internal-qa and release dependency

azure/azure-release-pipeline.yml, docker/sync-wrap/src/app.postman.spec.js, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js
=> Mm apm 1375 sync with timeouts

.github/workflows/continuous-integration.yml, pyproject.toml, scripts/calculate_version.py
=> apm-1442: this needs tagging to trigger release

Makefile, docker/sync-wrap/src/handlers.js
=> AEA-679 Changes to support EPS

.github/workflows/continuous-integration.yml
=> APM-1623 Add ACTIONS_ALLOW_UNSECURE_COMMANDS to set-env action

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, docker/sync-wrap/src/app.postman.spec.js, docker/sync-wrap/src/handlers.js, proxies/live/apiproxy/targets/apim.xml
=> apm-1552: use hosted apis target server

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
=> apm-1552: remove pinned utils version

.dependabot/config.yml, .gitignore, Makefile, azure/azure-pr-pipeline.yml, azure/templates/tests.yml, docker/async-slowapp/src/app.js, docker/async-slowapp/src/app.spec.js, docker/async-slowapp/src/handlers.js, docker/sync-wrap/src/app.google.spec.js, docker/sync-wrap/src/app.js, docker/sync-wrap/src/app.postman.spec.js, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js, e2e/Dockerfile, e2e/Makefile, e2e/api_tests.py, e2e/conftest.py, e2e/helpers.py, e2e/poetry.lock, e2e/poetry.toml, e2e/pyproject.toml, e2e/pytest.ini, ecs-proxies-deploy.yml, proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
=> Mm apm 1552 more explicit status response

azure/azure-release-pipeline.yml
=> apm-1351: missed service name parameter

azure/azure-release-pipeline.yml, e2e/tests/api_tests.py
=> apm-1351: increase wait for api to be provisioned

docker/sync-wrap/src/app.js, docker/sync-wrap/src/app.postman.spec.js, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js, e2e/tests/api_tests.py
- Fix sleep between poll requests.
- Add agent status to _status endpoint so we can monitor the number of open sockets and queued requests.
- Increase max sockets and free sockets by a factor of 10.
=> AEA-995: Performance improvements.

e2e/tests/api_tests.py
=> APM-1710 add retries to 504 and 418 tests

azure/azure-release-pipeline.yml, ecs-proxies-deploy.yml
=> apm-1600: test pr with autoscaling

azure/azure-release-pipeline.yml
=> apm-1717: sync wrap prod

azure/azure-release-pipeline.yml, docker/async-slowapp/package-lock.json, docker/async-slowapp/package.json, docker/async-slowapp/src/app.js, docker/async-slowapp/src/app.spec.js, docker/async-slowapp/src/handlers.js, docker/sync-wrap/package-lock.json, docker/sync-wrap/package.json, docker/sync-wrap/src/app.google.spec.js, docker/sync-wrap/src/app.js, docker/sync-wrap/src/app.postman.spec.js, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js
=> apm-1717: add api monitoring and better logging

docker/sync-wrap/package-lock.json, docker/sync-wrap/package.json, docker/sync-wrap/src/app.js, docker/sync-wrap/src/handlers.js
=> apm-1717: remove agent keepalive from sync-wrap

manifest_template.yml
=> APM-1572 Add manifest_template.yml

docker/async-slowapp/package-lock.json, docker/sync-wrap/package-lock.json, docker/sync-wrap/package.json, docker/sync-wrap/src/app.google.spec.js, docker/sync-wrap/src/app.js, docker/sync-wrap/src/app.postman.spec.js, e2e/pyproject.toml, ecs-proxies-deploy.yml
=> apm-1486: switch to egress proxy

docker/async-slowapp/package.json, docker/async-slowapp/src/handlers.js, docker/sync-wrap/package.json, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js
=> Dh apmspii 526 remove content location check from polling loop

azure/azure-build-pipeline.yml, azure/templates/e2e.yml
=> apm-2006: remove cache aliases

docker/sync-wrap/src/handlers.js, e2e/tests/api_tests.py
=> apm-2006: set timeout back to 60sec

docker/async-slowapp/src/app.js, docker/async-slowapp/src/app.spec.js, docker/sync-wrap/src/app.slowapp.spec.js, docker/sync-wrap/src/handlers.js, e2e/tests/api_tests.py
=> apm: set content-length=0 for errors with no response stream

docker/async-slowapp/package-lock.json, docker/async-slowapp/package.json, docker/sync-wrap/package-lock.json, docker/sync-wrap/package.json
Update supertest to fix high alert
=> APM-6136 update supertest

.github/README.md, .github/scripts/grype_json_to_csv.py, .github/scripts/sbom_json_to_csv.py, .github/scripts/sbom_packages_to_csv.py, .github/workflows/sbom.yml, azure/azure-build-pipeline.yml, scripts/create-sbom.sh, scripts/update-sbom.py
=> Added new SBOM config for generation all 3 reports

azure/azure-build-pipeline.yml
=> update azure build
